### ISSUE TITLE
Ability to convert verbose CRON schedules into clean text descriptions

### ISSUE THREAD

**Issue by TDola** [bradymholt/cRonstrue#125] opened 2019-08-21 15:50 UTC
Given a cron schedule of
```
00 07 01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31 1,2,3,4,5,6,7,8,9,10,11,12 1
```

It will produce 

```
At 07:00 AM, on day 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, and 31 of the month, and on Monday, only in January, February, March, April, May, June, July, August, September, October, November, and December
```

When it should really just say `Every Monday at 7:00 AM`

I am trying to use this library to create a human readable schedule description.

This is what my page looks like

![image](https://user-images.githubusercontent.com/30079906/63446740-5b297b00-c400-11e9-8dfe-51d34d5d0ef0.png)

and this is my basic code

```javascript
function scheduleDescription () {
  var params = $('#Report_Scheduler').serializeArray();
  var minutes = [];
  var hours = [];
  var daysOfMonths = [];
  var months = [];
  var weekDays = [];
  params.forEach(function (param) {
    switch (param.name) {
      case 'minute[]':
        minutes.push(param.value)
        break;
      case 'hour[]':
        hours.push(param.value)
        break;
      case 'day_of_month[]':
        daysOfMonths.push(param.value)
        break;
      case 'month[]':
        months.push(param.value)
        break;
      case 'week_day[]':
        weekDays.push(param.value)
        break;
    }
  })
  // Before doing anything. verify everything has a value
  var niceMessage = '';
  var hasError = false;
  if (minutes.length === 0) {
    niceMessage = 'Please select scheduled minutes';
    hasError = true;
  }
  if (hours.length === 0) {
    niceMessage = 'Please select scheduled hours';
    hasError = true;
  }
  if (daysOfMonths.length === 0) {
    niceMessage = 'Please select scheduled days';
    hasError = true;
  }
  if (months.length === 0) {
    niceMessage = 'Please select scheduled months';
    hasError = true;
  }
  if (weekDays.length === 0) {
    niceMessage = 'Please select scheduled week days';
    hasError = true;
  }
  if (!hasError) {
    var cronSechedule = [minutes.join(','), hours.join(','), daysOfMonths.join(','), months.join(','), weekDays.join(',')].join(' ');
    var cronstrue = window.cronstrue;
    niceMessage = cronstrue.toString(cronSechedule);
  }
  console.log(niceMessage)
}
```

I am not certain if this is truly an issue for this library to solve, so if you feel it is not, I can close this issue

**Comment by bradymholt** [comment] 2019-08-21 16:35
@TDola - Thanks for this issue but I think getting your expected output here would require a bit more logic than cRonstrue was intended to handle.  There might be some clever ways to handle this in the `transformVerbosity` function but I'm not sure offhand.  I'm going to close this one out for now.  Thank you.

**Closed** 2019-08-21 16:36 UTC

**Comment by TDola** [comment] 2019-08-21 16:38
No problem, I modified my code like so to account for it.

```javascript
function scheduleDescription () {
  var params = $('#Report_Scheduler').serializeArray();
  var minutes = [];
  var hours = [];
  var daysOfMonths = [];
  var months = [];
  var weekDays = [];
  params.forEach(function (param) {
    switch (param.name) {
      case 'minute[]':
        minutes.push(parseFloat(param.value))
        break;
      case 'hour[]':
        hours.push(parseFloat(param.value))
        break;
      case 'day_of_month[]':
        daysOfMonths.push(parseFloat(param.value))
        break;
      case 'month[]':
        months.push(parseFloat(param.value))
        break;
      case 'week_day[]':
        weekDays.push(parseFloat(param.value))
        break;
    }
  })
  // Before doing anything. verify everything has a value
  var niceMessage = '';
  var hasError = false;
  if (minutes.length === 0) {
    niceMessage = 'Please select scheduled minutes';
    hasError = true;
  }
  if (hours.length === 0) {
    niceMessage = 'Please select scheduled hours';
    hasError = true;
  }
  if (daysOfMonths.length === 0) {
    niceMessage = 'Please select scheduled days';
    hasError = true;
  }
  if (months.length === 0) {
    niceMessage = 'Please select scheduled months';
    hasError = true;
  }
  if (weekDays.length === 0) {
    niceMessage = 'Please select scheduled week days';
    hasError = true;
  }

  function calculateShortenedSchedule (schedules, max) {
    var schedGroupings = [];
    schedules.forEach(function (sched, index) {
      if (index === 0) {
        schedGroupings = [[sched]];
      } else {
        if (schedules[index - 1] + 1 === sched) {
          schedGroupings[schedGroupings.length - 1].push(sched);
        } else {
          schedGroupings.push([sched]);
        }
      }
    })
    var schedSchedule = '';
    schedGroupings.forEach(function (group, index) {
      if (group.length === max) {
        schedSchedule = '*';
      } else if (group.length > 2) {
        schedSchedule += group[0] + '-' + group[group.length - 1];
      } else {
        schedSchedule += group.join(',');
      }
      if (index !== schedGroupings.length - 1) {
        schedSchedule += ',';
      }
    })
    return schedSchedule;
  }

  if (!hasError) {
    var hoursSchedule = calculateShortenedSchedule(hours, 24);
    var daySchedule = calculateShortenedSchedule(daysOfMonths, 31);
    var monthSchedule = calculateShortenedSchedule(months, 12);
    var weekDaysSchedule = calculateShortenedSchedule(weekDays, 7);

    var cronSechedule = [minutes.join(','), hoursSchedule, daySchedule, monthSchedule, weekDaysSchedule].join(' ');
    console.log(cronSechedule)
    var cronstrue = window.cronstrue;
    niceMessage = cronstrue.toString(cronSechedule);
  }
  $('#cron_description').text(niceMessage);
}

```
