### ISSUE TITLE
Invalid translation: the first and the third weekday of the month

### ISSUE THREAD

**Issue by fracz** [bradymholt/cRonstrue#282] opened 2023-05-09 08:08 UTC
**Cron Expression**
`0 14 * * THU#1,THU#3`

**Expected Output**
"At 02:00 PM, on the first Thursday and the third Thursday of the month"

or

"At 02:00 PM, on the first and the third Thursday of the month"

**Actual Output**
"At 02:00 PM, on the null Thursday and Thursday of the month"

**Prerequisites**
- [x] The cron expression being passed in is a valid expression.  cRonstrue does not validate expressions and assumes the one you pass is already valid.  See the [FAQ](https://github.com/bradymholt/cRonstrue#frequently-asked-questions) for more details.

**Comment by bradymholt** [comment] 2023-05-09 12:43
I would welcome a PR to fix this.

**Comment by bradymholt** [comment] 2023-05-09 12:44
Duplicate of https://github.com/bradymholt/cRonstrue/issues/199

**Closed by bradymholt** 2023-05-09 12:44 UTC
